kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
    - "npm ci"
    - "npm run build"

- name: publish
  image: plugins/npm
  settings:
    username: dschroer
    password:
      from_secret: npm_password
    email: dominick@schroer.ca